### ISSUE TITLE
Phantom Card

### ISSUE THREAD

**Issue by kwiwkwiw** [thatjsprof/games_js#1]
There's always one of these per game that gives this error when clicked, I've checked over the line of code and the rest of the code because I retype it instead of downloading so I can get used to coding, _I'm very new_.
It's not that intrusive but it keeps the game from showing the You Win text

This time it happened to be the card I marked but its random each time
error message: `Uncaught TypeError: Cannot read property 'img' of undefined at HTMLImageElement.clickCard (app.js:77)`
![image](https://user-images.githubusercontent.com/79296549/108455734-c2fe9300-723c-11eb-83b9-b5ddc1b94938.png)

**Comment by thatjsprof** [comment]
Okay I'll look into it

**Comment by thatjsprof** [comment]
Okay I've resolved it. The fisher yates algorithm I used needed to have the length of the array reduced by 1. Without this, when it does the switching of values there would be a final value it would set as undefined hence the error you were getting. I've also updated the code. Thanks for pointing this out.

**Comment by thatjsprof** [comment]
The fisher yates algorithm is for sorting
